[package]
name = "rust-inekf"
version = "0.1.0"
edition = "2024"
authors = [
  "Lucas Libshutz <lsl94@cornell.edu>"
]

[workspace]
members = ["xtask"]
default-members = ["."]

[dependencies]
zenoh = "1.9.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"]}
nalgebra = { version = "0.35", features = ["serde-serialize"]}
serde = { version="1", features = ["derive"]}
serde_json = "1"
anyhow = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"]}
clap = { version = "4", features = ["derive"]}

[dev-dependencies]
approx = "0.5"
proptest = "1"
criterion = "0.8.2"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs/katex-header.html"]
