use anyhow::{bail, Context, Result};
use std::{env, fs, path::{Path, PathBuf}, process::Command};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()
}

fn run(cmd: &mut Command) -> Result<()> {
    let status = cmd.status().with_context(|| format!("could not spawn {cmd:?}"))?;
    if !status.success() {
        bail!("{cmd:?} failed with {status}");
    }
    Ok(())
}

fn copy_dir(from: &Path, to: &Path) -> Result<()> {
    fs::create_dir_all(to)?;
    for entry in fs::read_dir(from)? {
        let entry = entry?;
        let dest = to.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_dir(&entry.path(), &dest)?;
        } else {
            fs::copy(entry.path(), &dest)?;
        }
    }
    Ok(())
}

fn brace_body(s: &str) -> Result<String> {
    let b = s.as_bytes();
    if b.first() != Some(&b'{') {
        bail!("expected `{{`");
    }
    let (mut depth, mut i) = (0usize, 0usize);
    while i < b.len() {
        match b[i] {
            b'\\' => { i += 2; continue; } // skip escaped characters
            b'{' => depth += 1,
            b'}' => { depth -= 1; if depth == 0 { return Ok(s[1..i].to_string()); } }
            _ => {}
        }
        i += 1;
    }
    bail!("unbalanced braces")
}

fn parse_sty(src: &str) -> Result<Vec<(String, String)>> {
    let mut out = Vec::new();
    for (n, raw) in src.lines().enumerate() {
        let line = raw.split('%').next().unwrap_or("").trim();
        if line.is_empty() { continue; }

        let rest = line
            .strip_prefix("\\newcommand")
            .or_else(|| line.strip_prefix("\\renewcommand"))
            .with_context(|| format!("line {}: unsupported directive: {line}", n + 1))?;

        let rest = rest.trim_start().strip_prefix('{').unwrap_or(rest.trim_start());
        let rest = rest.strip_prefix('\\')
            .with_context(|| format!("line {}: expected a macro name", n + 1))?;
        let end = rest.find(|c: char| !c.is_ascii_alphabetic()).unwrap_or(rest.len());
        let (name, mut rest) = rest.split_at(end);
        rest = rest.trim_start_matches('}').trim_start();

        // Discard the [n] arity — KaTeX infers it from the highest #n in the body.
        if rest.starts_with('[') {
            let close = rest.find(']').context("unterminated [n]")?;
            rest = rest[close + 1..].trim_start();
        }
        out.push((name.to_string(), brace_body(rest)
            .with_context(|| format!("line {}: unbalanced braces", n + 1))?));
    }
    Ok(out)
}

fn js_string(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

fn macros() -> Result<()> {
    let root = root();
    let sty = fs::read_to_string(root.join("docs/macros.sty"))
        .context("docs/macros.sty not found")?;
    let defs = parse_sty(&sty)?;

    // 1. mdbook-katex format
    let txt: String = defs.iter().map(|(n, b)| format!("\\{n}:{{{b}}}\n")).collect();
    fs::write(root.join("docs/macros.txt"), txt)?;

    // 2. rustdoc header, with the same macros as a KaTeX `macros` object
    let entries: Vec<String> = defs.iter()
        .map(|(n, b)| format!("    \"\\\\{n}\": {}", js_string(b)))
        .collect();
    fs::write(root.join("docs/katex-header.html"), format!(
r#"<!-- GENERATED by `cargo xtask macros` from docs/macros.sty. Do not edit. -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script>
<script>
  window.katexMacros = {{
{}
  }};
</script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js"
  onload="renderMathInElement(document.body, {{
    delimiters: [
      {{left:'$$', right:'$$', display:true}},
      {{left:'\\(', right:'\\)', display:false}}
    ],
    macros: window.katexMacros
  }});"></script>
"#, entries.join(",\n")))?;

    println!("generated {} macros", defs.len());
    Ok(())
}

fn watch() -> Result<()> {
    macros()?;
    let root = root();
    let header = fs::canonicalize(root.join("docs/katex-header.html"))?;

    let mut book = Command::new("mdbook")
        .current_dir(&root)
        .args(["serve", "docs", "--open"])
        .spawn()
        .context("mdbook not on PATH")?;

    let mut api = Command::new("cargo")
        .current_dir(&root)
        .args(["watch", "-w", "src", "-x", "doc --no-deps -p rust-inekf"])
        .env("RUSTDOCFLAGS", format!("--html-in-header {}", header.display()))
        .spawn()
        .context("cargo-watch not installed")?;

    book.wait()?;      // blocks until you Ctrl-C
    let _ = api.kill(); // safety net; Ctrl-C usually reaches both
    Ok(())
}

fn docs(open: bool) -> Result<()> {
    macros()?;
    let root = root();
    let header = fs::canonicalize(root.join("docs/katex-header.html"))
        .context("docs/katex-header.html not found")?;
    // rustdoc resolves --html-in-header against the CWD, not the manifest.
    // so this path must be absolute.
    run(Command::new("cargo")
        .current_dir(&root)
        .args(["doc", "--no-deps", "-p", "rust-inekf"])
        .env("RUSTDOCFLAGS", format!("--html-in-header {}", header.display())))?;

    run(Command::new("mdbook")
        .current_dir(&root)
        .args(["build", "docs"]))?;

    // Nest the API reference inside the book so one directory is deployable.
    copy_dir(&root.join("target/doc"), &root.join("docs/book/api"))?;

    if open {
        let index = root.join("docs/book/index.html");
        run(Command::new(if cfg!(target_os = "macos") { "open" } else { "xdg-open" })
            .arg(index))?;
    }
    Ok(())
}

fn main() -> Result<()> {
    let args: Vec<String> = env::args().collect();
    match args.get(1).map(String::as_str) {
        Some("docs") => docs(args.iter().any(|a| a == "--open")),
        Some("watch") => watch(),
        Some("macros") => macros(),
        _ => {
            Ok(())
        }
    }
}
